# 自动标签规则 - 根据文件路径自动添加标签

feature:
  - changed-files:
    - any-glob-to-any-file: 'main/src/features/**/*'

fix:
  - changed-files:
    - any-glob-to-any-file: 
      - 'main/src/**/*.ts'
      - 'main/src/**/*.js'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '**/*.md'
      - 'README.md'

test:
  - changed-files:
    - any-glob-to-any-file:
      - 'main/test/**/*'
      - '**/*.test.ts'
      - '**/*.spec.ts'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '**/package.json'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'Dockerfile'
      - 'docker-compose.yml'
